### PR TITLE
refactor code and handle division by 0 error if exist

### PR DESCRIPTION
**Pull request by kishyassin**
This pull request includes several changes aimed at refactoring the Kids Reward System application. The main improvements include moving inline styles to an external stylesheet, adding new utility functions, and enhancing data handling and security.

### Refactoring and Code Organization:
* Moved inline styles from `add.php`, `index.php`, `pay.php`, and `remove.php` to a new external stylesheet `styles.css`. [[1]](diffhunk://#diff-87172570937491c46959d02cff87ee97841f68b2c32edcf81575072b24aadc1fL6-L19) [[2]](diffhunk://#diff-7413d6453f901e939bbd840c8f0d1c7b20c2ca0e7f71741e4e07c6cf036f16c0R1-R46) [[3]](diffhunk://#diff-335653b328c14159f2603d88e4d46b26f1452f7c5189e4113fa1f6585f403f25L6-L19) [[4]](diffhunk://#diff-dcb2efff23f74208bff8ca798d3a0a0f66f2e82f814ffc2f1b4a52c599705544L6-R6) [[5]](diffhunk://#diff-380b7b38760dd442e897eb0164c58f6a17da966ccaca6318017a468c163979b1R1-R73)

### New Utility Functions:
* Added utility functions in `config.php` for calculating percentages, determining active days, and displaying icons.

### Data Handling and Security:
* Enhanced data handling by using the `htmlspecialchars` function to prevent XSS attacks in `index.php`.

### CODE REVIEW

**Comment by lukelloyd1985** [comment]
@kishyassin, thanks a lot for the PR to fix & improve the code 😎

Can I just get you to...
- sort the indentation (2 spaces) on the modified/added code
- reinstate "example-kids.json"

**Comment by lukelloyd1985** [comment]
> sort the indentation (2 spaces) on the modified/added code
> reinstate "example-kids.json"

@kishyassin, if you could please just sort the final indentation I've flagged in the review and I'll be happy to approve & merge the PR 😎

**Comment by lukelloyd1985** [comment]
> @lukelloyd1985 , I couldn’t find any flagged lines. Could you point me to the specific areas or provide an example of what needs fixing? Thanks! 🙏
> 

@kishyassin, sure 👍🏻

In add.php at line 6: your <link> tag needs 2x less spaces (so it's the same indentation as <title> tag)

**Comment by kishyassin** [comment]
well done 👍🏻

**Review by lukelloyd1985 — APPROVED** [review]

**Comment by lukelloyd1985** [comment]
@kishyassin, thanks a lot for the PR 😎

It has been merged to main, I tested it on my dev system and all looks ok so released as v1.4.0 👍👊

**Comment by kishyassin** [comment]
good job, thank you 👍

**Pull request merged**
